repos:
-   repo: local
    hooks:
    # -   id: check-added-large-files
    # -   id: check-case-conflict
    # -   id: check-executables-have-shebangs
    # -   id: check-merge-conflict
    # -   id: check-shebang-scripts-are-executable
    # -   id: check-symlinks
    # -   id: check-yaml
    # -   id: debug-statements
    #     exclude: tests/
    # -   id: destroyed-symlinks
    # -   id: end-of-file-fixer
    #     exclude: tests/test_changes/
    #     files: \.(py|sh|rst|yml|yaml)$
    # -   id: mixed-line-ending
    # -   id: trailing-whitespace
    #     name: trailing-whitespace
    #     files: \.(py|sh|rst|yml|yaml)$
    -   id: black
        name: black
        entry: black
        exclude: tests/
        language: python
        types: [python]
    -   id: flake8
        name: flake8
        entry: flake8
        args: [
            '--max-line-length=88',
            '--extend-ignore=E203, E501, D200, D100, D209, D400, D104, D102, D205, BLK100, D401, D202, D107',
        ]
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'pydocstyle>=5.0.0',
        ]
        language: python
        types: [python]
        exclude: ^tests/
    # -   id: blacken-docs
    #     name: blacken-docs
    #     additional_dependencies: [black]
    #     exclude: ^.github/
    # -   id: rstcheck
    #     name: rstcheck
    #     args: [
    #         --report-level=warning,
    #     ]
    # -   id: codespell
    #     name: codespell
    #     files: \.(py|sh|rst|yml|yaml)$
# ci:
#     # Settings for the https://pre-commit.ci/ continuous integration service
#     autofix_prs: false
#     # Default message is more verbose
#     autoupdate_commit_msg: '[pre-commit.ci] autoupdate'
#     # Default is weekly
#     autoupdate_schedule: monthly